### ISSUE TITLE
Diode(1N4148 : D10, D11, D20, D21) foot pattern is more bit large.

### ISSUE THREAD

**Issue by takurx** [tomorrow56/M5Stack_DVM#3]
Diode(1N4148 : D10, D11, D20, D21) foot pattern need more bit large.
It's minor error, it can recover for hand.

![M5stack_DVM](https://user-images.githubusercontent.com/6850122/88002062-936b9900-cb3c-11ea-89b4-b7ca8d72c0a6.jpg)

**Comment by tomorrow56** [comment]
Thank you for checking.
At the next modification, the macro of the component will be modified.
